theme: minima
Title: My First GitHub Blog!
author: Lauren S
description: I have been learning how navigate through GitHub and i am now understanding the basics. Here is my first blog/page using GitHub.

